apiVersion: apps/v1
kind: Deployment
metadata:
  name: seclock
  namespace: seclock
  labels:
    app: seclock
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: seclock
  template:
    metadata:
      labels:
        app: seclock
    spec:
      containers:
      - name: seclock
        image: 773135747657.dkr.ecr.ap-south-1.amazonaws.com/seclock:3d0e1a3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
